### ISSUE TITLE
Webhooks query Collection with Variations inside

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#309] opened 2018-09-28 10:59 UTC
Hi,

i have an Issue with sending an Post Request via Webhook with Collection Data inside.
I have following Query:

```
"query {

content { content_types { ... on AdventuresContentContentContent_typesTextVariant { text } ... on AdventuresContentContentContent_typesImage_and_textVariant { text }}}

, id, content_headline: headline, content_description: description}"
```

If i remove the _content { content_types_ part of the query the Webhook is working.
Any Idea ?

**Comment by stefan-kamsker** [comment] 2018-09-28 11:05
hi, i will have a look

**Comment by Clonk-HTML5** [comment] 2018-09-28 11:16
Ahh i found:

```
Unknown type "AdventuresContentContentContent_typesTextVariant
```

but if i try it in graphiql it works.

**Comment by Clonk-HTML5** [comment] 2018-10-01 11:02
Did you figured out something ?

There is Something with the WebhookManager:
```php
$result = GraphQL::executeQuery(new Schema(['query' => $type]), $webhook->getQuery(), $content);
```

**Comment by stefan-kamsker** [comment] 2018-10-01 11:59
hi,

sorry, not yet, still investigating

the problem is, that those inline fragments (eg. AdventuresContentContentContent_typesTextVariant ) are not available (or not under that name) in this context (querying only the current object)

Best regards!

**Comment by stefan-kamsker** [comment] 2018-10-02 10:52
same problem for previews, variant schema types are not registered in this context.

i will check it together with @franzwilding later, I'm failing here

Best regards!

**Comment by franzwilding** [comment] 2018-10-04 10:58
Thank you @Clonk-HTML5 & @stefan-kamsker for the report and debugging information. This problem should be fixed now for preview and webhooks.

**Closed** 2018-10-04 10:57 UTC
Labels: bug
